# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M08GQQ20sDbB91cG5IhtK10EPppQsTzH
"""

import random
def game():
  choices=['rock','paper','scissors']
  while True:
    user_choice=input("enter your choice (rock/paper/scissors)or 'q'to quit:").lower()
    if user_choice=='q':
      break
    if user_choice not in choices:
      print("invalid choice! please try again")
      continue
    computer_choice=random.choice(choices)
    print(f"\nYou choose:{user_choice}")
    print(f"\nComputer choose:{computer_choice}\n")
    if user_choice==computer_choice:
      print("tie!")
    elif (user_choice=='rock' and computer_choice=='scissors')or\
         (user_choice=='paper' and computer_choice=='rock')or\
         (user_choice=='scissors' and computer_choice=='paper'):
      print("You win!")
    else:
      print("Computer win!")
game()